/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WishesRouteImport } from './routes/wishes'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as OurTimeRouteImport } from './routes/our-time'
import { Route as JourneyRouteImport } from './routes/journey'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as GamesRouteImport } from './routes/games'
import { Route as IndexRouteImport } from './routes/index'

const WishesRoute = WishesRouteImport.update({
  id: '/wishes',
  path: '/wishes',
  getParentRoute: () => rootRouteImport,
} as any)
const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTimeRoute = OurTimeRouteImport.update({
  id: '/our-time',
  path: '/our-time',
  getParentRoute: () => rootRouteImport,
} as any)
const JourneyRoute = JourneyRouteImport.update({
  id: '/journey',
  path: '/journey',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/garden': typeof GardenRoute
  '/journey': typeof JourneyRoute
  '/our-time': typeof OurTimeRoute
  '/timeline': typeof TimelineRoute
  '/wishes': typeof WishesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/garden': typeof GardenRoute
  '/journey': typeof JourneyRoute
  '/our-time': typeof OurTimeRoute
  '/timeline': typeof TimelineRoute
  '/wishes': typeof WishesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/garden': typeof GardenRoute
  '/journey': typeof JourneyRoute
  '/our-time': typeof OurTimeRoute
  '/timeline': typeof TimelineRoute
  '/wishes': typeof WishesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/garden'
    | '/journey'
    | '/our-time'
    | '/timeline'
    | '/wishes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games'
    | '/garden'
    | '/journey'
    | '/our-time'
    | '/timeline'
    | '/wishes'
  id:
    | '__root__'
    | '/'
    | '/games'
    | '/garden'
    | '/journey'
    | '/our-time'
    | '/timeline'
    | '/wishes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRoute
  GardenRoute: typeof GardenRoute
  JourneyRoute: typeof JourneyRoute
  OurTimeRoute: typeof OurTimeRoute
  TimelineRoute: typeof TimelineRoute
  WishesRoute: typeof WishesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wishes': {
      id: '/wishes'
      path: '/wishes'
      fullPath: '/wishes'
      preLoaderRoute: typeof WishesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-time': {
      id: '/our-time'
      path: '/our-time'
      fullPath: '/our-time'
      preLoaderRoute: typeof OurTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journey': {
      id: '/journey'
      path: '/journey'
      fullPath: '/journey'
      preLoaderRoute: typeof JourneyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRoute,
  GardenRoute: GardenRoute,
  JourneyRoute: JourneyRoute,
  OurTimeRoute: OurTimeRoute,
  TimelineRoute: TimelineRoute,
  WishesRoute: WishesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
